name: Workflow Concorrencia
run-name: Workflow Concorrencia ${{github.run_number}}
on:
    workflow_dispatch:
        inputs:
            chave:
                type: string
                default: pipeline-aula
concurrency: ${{inputs.chave}}
# concurrency: pipeline-aula        # teste de concorrencia 1
jobs:
    fluxo-01:
        runs-on: ubuntu-latest
        steps:
            - name: Job teste
              run: |
                sleep 120;
                echo "Action exec Job 1"