name: Deploy Fake com Secret
on:
    workflow_call:
        secrets:
            ambiente:
                required: true
                description: "Ambiente do deploy"
jobs:
    deploy-to-k8s:
        runs-on: ubuntu-latest  
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{secrets.ambiente}}"