name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job: 
    name: "Meu primeiro-job"
    runs-on: ubuntu-latest
    steps:
      - name: "minha primeira ação"
        run: echo "Hello World !!"
      - name: "segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow"
          echo "Parabéns !!!"
      - name: "Script Python"
        run: |
          var = "Hello from Python"
          print(var)
        shell: python
  segundo-job:
    name: "Intalação do Ambiente NODEJS"
    runs-on: ubuntu-latest
    steps:
      - name: "verificação da versão do NodeJs"
        run: node --version
