name: WorkFlow Matrix
on:
    workflow_dispatch:
jobs:
    fluxo-execucao:
        strategy:
            matrix:
                version: [16,18,20]
                platform: ["windows","ubuntu"]
        runs-on: "${{matrix.platform}}-latest"
        steps:
            - name: Instalação Node
              uses: actions/setup-node@v6
              with:
                node-version: ${{matrix.version}}
                
            - name: Exibition Version e Platform
              run: |
                node --version
                echo ${{runner.os}}