name: Evento Pull Request
on:
    pull_request:
        branches: ["main"]
        types: closed
        
jobs:
    teste:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            
            - name: Action Teste
              run: echo "Action executada em main e feature "

            - name: Alteração no card
              uses: actions/github-script@v8
              with:
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Adding comment here about PR'
                        })