name: Evento Push
on:
    push:
        # branches: ["main", "feature/*"]
        tags:
            - v*

jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            
            - name: Action Teste
              run: echo "Action executada em main e feature "
