name: Evento Push
on:
    workflow_dispatch: # só para não dar erro
    # push:
    #     branches: ["main", "feature/*"]
        # branches-ignore:
        # path-ignore:
        # paths:
        #     - "src/**"
        # tags:
        #     - v*

jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            
            - name: Action Teste
              run: echo "Action executada em main e feature "
