name: Evento Operações
on:
    workflow_dispatch:  
        inputs:
            valor-numerico:
                type: number
                default: 20

            valor-string:
                type: string
                default: "XPTO"

            valor-boolean:
                type: boolean
                default: true
                
jobs:
    teste:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            
            - name: Operação com String
              run: echo "${{github.actor == inputs.valor-string}}"

            - name: Operação com Number
              run: echo "${{inputs.valor-numerico > 20}}"

            - name: Operação com Boolean
              run: echo "${{!inputs.valor-boolean}}"