name: Workflow Status Steps
on:
    push:
jobs:
    fluxo-01:
        runs-on: ubuntu-latest
        steps:
            - name: Will Fail
              run: l

    fluxo-02:
        runs-on: ubuntu-latest
        needs: [fluxo-01]
        steps: 
            - name: Success execution
              run: echo "Success Exec"